sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 5

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - composer install

before_script:
  - composer validate

script:
  - ./vendor/bin/codecept run unit
